# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stefan/RoboYacht/svn/avalon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stefan/RoboYacht/svn/avalon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefan/RoboYacht/svn/avalon/CMakeFiles /home/stefan/RoboYacht/svn/avalon/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stefan/RoboYacht/svn/avalon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aisEval

# Build rule for target.
aisEval: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aisEval
.PHONY : aisEval

# fast build rule for target.
aisEval/fast:
	$(MAKE) -f CMakeFiles/aisEval.dir/build.make CMakeFiles/aisEval.dir/build
.PHONY : aisEval/fast

#=============================================================================
# Target rules for targets named destination_converter

# Build rule for target.
destination_converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 destination_converter
.PHONY : destination_converter

# fast build rule for target.
destination_converter/fast:
	$(MAKE) -f CMakeFiles/destination_converter.dir/build.make CMakeFiles/destination_converter.dir/build
.PHONY : destination_converter/fast

#=============================================================================
# Target rules for targets named dtom

# Build rule for target.
dtom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dtom
.PHONY : dtom

# fast build rule for target.
dtom/fast:
	$(MAKE) -f CMakeFiles/dtom.dir/build.make CMakeFiles/dtom.dir/build
.PHONY : dtom/fast

#=============================================================================
# Target rules for targets named eposdebug

# Build rule for target.
eposdebug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eposdebug
.PHONY : eposdebug

# fast build rule for target.
eposdebug/fast:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/build
.PHONY : eposdebug/fast

#=============================================================================
# Target rules for targets named flag-checker

# Build rule for target.
flag-checker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flag-checker
.PHONY : flag-checker

# fast build rule for target.
flag-checker/fast:
	$(MAKE) -f CMakeFiles/flag-checker.dir/build.make CMakeFiles/flag-checker.dir/build
.PHONY : flag-checker/fast

#=============================================================================
# Target rules for targets named global_skipper

# Build rule for target.
global_skipper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 global_skipper
.PHONY : global_skipper

# fast build rule for target.
global_skipper/fast:
	$(MAKE) -f CMakeFiles/global_skipper.dir/build.make CMakeFiles/global_skipper.dir/build
.PHONY : global_skipper/fast

#=============================================================================
# Target rules for targets named gps

# Build rule for target.
gps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gps
.PHONY : gps

# fast build rule for target.
gps/fast:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/build
.PHONY : gps/fast

#=============================================================================
# Target rules for targets named imucleaner

# Build rule for target.
imucleaner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imucleaner
.PHONY : imucleaner

# fast build rule for target.
imucleaner/fast:
	$(MAKE) -f CMakeFiles/imucleaner.dir/build.make CMakeFiles/imucleaner.dir/build
.PHONY : imucleaner/fast

#=============================================================================
# Target rules for targets named mtod

# Build rule for target.
mtod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mtod
.PHONY : mtod

# fast build rule for target.
mtod/fast:
	$(MAKE) -f CMakeFiles/mtod.dir/build.make CMakeFiles/mtod.dir/build
.PHONY : mtod/fast

#=============================================================================
# Target rules for targets named navigator

# Build rule for target.
navigator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 navigator
.PHONY : navigator

# fast build rule for target.
navigator/fast:
	$(MAKE) -f CMakeFiles/navigator.dir/build.make CMakeFiles/navigator.dir/build
.PHONY : navigator/fast

#=============================================================================
# Target rules for targets named obstacle_converter

# Build rule for target.
obstacle_converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obstacle_converter
.PHONY : obstacle_converter

# fast build rule for target.
obstacle_converter/fast:
	$(MAKE) -f CMakeFiles/obstacle_converter.dir/build.make CMakeFiles/obstacle_converter.dir/build
.PHONY : obstacle_converter/fast

#=============================================================================
# Target rules for targets named porttracker

# Build rule for target.
porttracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 porttracker
.PHONY : porttracker

# fast build rule for target.
porttracker/fast:
	$(MAKE) -f CMakeFiles/porttracker.dir/build.make CMakeFiles/porttracker.dir/build
.PHONY : porttracker/fast

#=============================================================================
# Target rules for targets named remotecontrol

# Build rule for target.
remotecontrol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 remotecontrol
.PHONY : remotecontrol

# fast build rule for target.
remotecontrol/fast:
	$(MAKE) -f CMakeFiles/remotecontrol.dir/build.make CMakeFiles/remotecontrol.dir/build
.PHONY : remotecontrol/fast

#=============================================================================
# Target rules for targets named rootsolver_test

# Build rule for target.
rootsolver_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rootsolver_test
.PHONY : rootsolver_test

# fast build rule for target.
rootsolver_test/fast:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/build
.PHONY : rootsolver_test/fast

#=============================================================================
# Target rules for targets named ruddermain

# Build rule for target.
ruddermain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ruddermain
.PHONY : ruddermain

# fast build rule for target.
ruddermain/fast:
	$(MAKE) -f CMakeFiles/ruddermain.dir/build.make CMakeFiles/ruddermain.dir/build
.PHONY : ruddermain/fast

#=============================================================================
# Target rules for targets named sailmain

# Build rule for target.
sailmain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sailmain
.PHONY : sailmain

# fast build rule for target.
sailmain/fast:
	$(MAKE) -f CMakeFiles/sailmain.dir/build.make CMakeFiles/sailmain.dir/build
.PHONY : sailmain/fast

#=============================================================================
# Target rules for targets named sailmain_keepalive

# Build rule for target.
sailmain_keepalive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sailmain_keepalive
.PHONY : sailmain_keepalive

# fast build rule for target.
sailmain_keepalive/fast:
	$(MAKE) -f CMakeFiles/sailmain_keepalive.dir/build.make CMakeFiles/sailmain_keepalive.dir/build
.PHONY : sailmain_keepalive/fast

#=============================================================================
# Target rules for targets named sailor_statemachine

# Build rule for target.
sailor_statemachine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sailor_statemachine
.PHONY : sailor_statemachine

# fast build rule for target.
sailor_statemachine/fast:
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/build
.PHONY : sailor_statemachine/fast

#=============================================================================
# Target rules for targets named sailor_transitions

# Build rule for target.
sailor_transitions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sailor_transitions
.PHONY : sailor_transitions

# fast build rule for target.
sailor_transitions/fast:
	$(MAKE) -f CMakeFiles/sailor_transitions.dir/build.make CMakeFiles/sailor_transitions.dir/build
.PHONY : sailor_transitions/fast

#=============================================================================
# Target rules for targets named simulator

# Build rule for target.
simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulator
.PHONY : simulator

# fast build rule for target.
simulator/fast:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/build
.PHONY : simulator/fast

#=============================================================================
# Target rules for targets named skipper

# Build rule for target.
skipper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skipper
.PHONY : skipper

# fast build rule for target.
skipper/fast:
	$(MAKE) -f CMakeFiles/skipper.dir/build.make CMakeFiles/skipper.dir/build
.PHONY : skipper/fast

#=============================================================================
# Target rules for targets named skipper2

# Build rule for target.
skipper2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skipper2
.PHONY : skipper2

# fast build rule for target.
skipper2/fast:
	$(MAKE) -f CMakeFiles/skipper2.dir/build.make CMakeFiles/skipper2.dir/build
.PHONY : skipper2/fast

#=============================================================================
# Target rules for targets named system-state

# Build rule for target.
system-state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system-state
.PHONY : system-state

# fast build rule for target.
system-state/fast:
	$(MAKE) -f CMakeFiles/system-state.dir/build.make CMakeFiles/system-state.dir/build
.PHONY : system-state/fast

#=============================================================================
# Target rules for targets named testaufruf

# Build rule for target.
testaufruf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testaufruf
.PHONY : testaufruf

# fast build rule for target.
testaufruf/fast:
	$(MAKE) -f CMakeFiles/testaufruf.dir/build.make CMakeFiles/testaufruf.dir/build
.PHONY : testaufruf/fast

#=============================================================================
# Target rules for targets named windcleaner

# Build rule for target.
windcleaner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 windcleaner
.PHONY : windcleaner

# fast build rule for target.
windcleaner/fast:
	$(MAKE) -f CMakeFiles/windcleaner.dir/build.make CMakeFiles/windcleaner.dir/build
.PHONY : windcleaner/fast

# target to build an object file
RudderMotor.o:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/RudderMotor.o
	$(MAKE) -f CMakeFiles/porttracker.dir/build.make CMakeFiles/porttracker.dir/RudderMotor.o
	$(MAKE) -f CMakeFiles/ruddermain.dir/build.make CMakeFiles/ruddermain.dir/RudderMotor.o
.PHONY : RudderMotor.o

# target to preprocess a source file
RudderMotor.i:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/RudderMotor.i
	$(MAKE) -f CMakeFiles/porttracker.dir/build.make CMakeFiles/porttracker.dir/RudderMotor.i
	$(MAKE) -f CMakeFiles/ruddermain.dir/build.make CMakeFiles/ruddermain.dir/RudderMotor.i
.PHONY : RudderMotor.i

# target to generate assembly for a file
RudderMotor.s:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/RudderMotor.s
	$(MAKE) -f CMakeFiles/porttracker.dir/build.make CMakeFiles/porttracker.dir/RudderMotor.s
	$(MAKE) -f CMakeFiles/ruddermain.dir/build.make CMakeFiles/ruddermain.dir/RudderMotor.s
.PHONY : RudderMotor.s

# target to build an object file
SailMotor.o:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/SailMotor.o
	$(MAKE) -f CMakeFiles/sailmain.dir/build.make CMakeFiles/sailmain.dir/SailMotor.o
.PHONY : SailMotor.o

# target to preprocess a source file
SailMotor.i:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/SailMotor.i
	$(MAKE) -f CMakeFiles/sailmain.dir/build.make CMakeFiles/sailmain.dir/SailMotor.i
.PHONY : SailMotor.i

# target to generate assembly for a file
SailMotor.s:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/SailMotor.s
	$(MAKE) -f CMakeFiles/sailmain.dir/build.make CMakeFiles/sailmain.dir/SailMotor.s
.PHONY : SailMotor.s

# target to build an object file
Ship.o:
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/Ship.o
	$(MAKE) -f CMakeFiles/sailor_transitions.dir/build.make CMakeFiles/sailor_transitions.dir/Ship.o
.PHONY : Ship.o

# target to preprocess a source file
Ship.i:
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/Ship.i
	$(MAKE) -f CMakeFiles/sailor_transitions.dir/build.make CMakeFiles/sailor_transitions.dir/Ship.i
.PHONY : Ship.i

# target to generate assembly for a file
Ship.s:
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/Ship.s
	$(MAKE) -f CMakeFiles/sailor_transitions.dir/build.make CMakeFiles/sailor_transitions.dir/Ship.s
.PHONY : Ship.s

# target to build an object file
aisEval.o:
	$(MAKE) -f CMakeFiles/aisEval.dir/build.make CMakeFiles/aisEval.dir/aisEval.o
.PHONY : aisEval.o

# target to preprocess a source file
aisEval.i:
	$(MAKE) -f CMakeFiles/aisEval.dir/build.make CMakeFiles/aisEval.dir/aisEval.i
.PHONY : aisEval.i

# target to generate assembly for a file
aisEval.s:
	$(MAKE) -f CMakeFiles/aisEval.dir/build.make CMakeFiles/aisEval.dir/aisEval.s
.PHONY : aisEval.s

# target to build an object file
destination_converter.o:
	$(MAKE) -f CMakeFiles/destination_converter.dir/build.make CMakeFiles/destination_converter.dir/destination_converter.o
.PHONY : destination_converter.o

# target to preprocess a source file
destination_converter.i:
	$(MAKE) -f CMakeFiles/destination_converter.dir/build.make CMakeFiles/destination_converter.dir/destination_converter.i
.PHONY : destination_converter.i

# target to generate assembly for a file
destination_converter.s:
	$(MAKE) -f CMakeFiles/destination_converter.dir/build.make CMakeFiles/destination_converter.dir/destination_converter.s
.PHONY : destination_converter.s

# target to build an object file
dtom.o:
	$(MAKE) -f CMakeFiles/dtom.dir/build.make CMakeFiles/dtom.dir/dtom.o
.PHONY : dtom.o

# target to preprocess a source file
dtom.i:
	$(MAKE) -f CMakeFiles/dtom.dir/build.make CMakeFiles/dtom.dir/dtom.i
.PHONY : dtom.i

# target to generate assembly for a file
dtom.s:
	$(MAKE) -f CMakeFiles/dtom.dir/build.make CMakeFiles/dtom.dir/dtom.s
.PHONY : dtom.s

# target to build an object file
eposdebug.o:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/eposdebug.o
.PHONY : eposdebug.o

# target to preprocess a source file
eposdebug.i:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/eposdebug.i
.PHONY : eposdebug.i

# target to generate assembly for a file
eposdebug.s:
	$(MAKE) -f CMakeFiles/eposdebug.dir/build.make CMakeFiles/eposdebug.dir/eposdebug.s
.PHONY : eposdebug.s

# target to build an object file
flag-checker.o:
	$(MAKE) -f CMakeFiles/flag-checker.dir/build.make CMakeFiles/flag-checker.dir/flag-checker.o
.PHONY : flag-checker.o

# target to preprocess a source file
flag-checker.i:
	$(MAKE) -f CMakeFiles/flag-checker.dir/build.make CMakeFiles/flag-checker.dir/flag-checker.i
.PHONY : flag-checker.i

# target to generate assembly for a file
flag-checker.s:
	$(MAKE) -f CMakeFiles/flag-checker.dir/build.make CMakeFiles/flag-checker.dir/flag-checker.s
.PHONY : flag-checker.s

# target to build an object file
global_skipper.o:
	$(MAKE) -f CMakeFiles/global_skipper.dir/build.make CMakeFiles/global_skipper.dir/global_skipper.o
.PHONY : global_skipper.o

# target to preprocess a source file
global_skipper.i:
	$(MAKE) -f CMakeFiles/global_skipper.dir/build.make CMakeFiles/global_skipper.dir/global_skipper.i
.PHONY : global_skipper.i

# target to generate assembly for a file
global_skipper.s:
	$(MAKE) -f CMakeFiles/global_skipper.dir/build.make CMakeFiles/global_skipper.dir/global_skipper.s
.PHONY : global_skipper.s

# target to build an object file
gps.o:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps.o
.PHONY : gps.o

# target to preprocess a source file
gps.i:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps.i
.PHONY : gps.i

# target to generate assembly for a file
gps.s:
	$(MAKE) -f CMakeFiles/gps.dir/build.make CMakeFiles/gps.dir/gps.s
.PHONY : gps.s

# target to build an object file
imucleaner.o:
	$(MAKE) -f CMakeFiles/imucleaner.dir/build.make CMakeFiles/imucleaner.dir/imucleaner.o
.PHONY : imucleaner.o

# target to preprocess a source file
imucleaner.i:
	$(MAKE) -f CMakeFiles/imucleaner.dir/build.make CMakeFiles/imucleaner.dir/imucleaner.i
.PHONY : imucleaner.i

# target to generate assembly for a file
imucleaner.s:
	$(MAKE) -f CMakeFiles/imucleaner.dir/build.make CMakeFiles/imucleaner.dir/imucleaner.s
.PHONY : imucleaner.s

# target to build an object file
mtod.o:
	$(MAKE) -f CMakeFiles/mtod.dir/build.make CMakeFiles/mtod.dir/mtod.o
.PHONY : mtod.o

# target to preprocess a source file
mtod.i:
	$(MAKE) -f CMakeFiles/mtod.dir/build.make CMakeFiles/mtod.dir/mtod.i
.PHONY : mtod.i

# target to generate assembly for a file
mtod.s:
	$(MAKE) -f CMakeFiles/mtod.dir/build.make CMakeFiles/mtod.dir/mtod.s
.PHONY : mtod.s

# target to build an object file
navigator.o:
	$(MAKE) -f CMakeFiles/navigator.dir/build.make CMakeFiles/navigator.dir/navigator.o
.PHONY : navigator.o

# target to preprocess a source file
navigator.i:
	$(MAKE) -f CMakeFiles/navigator.dir/build.make CMakeFiles/navigator.dir/navigator.i
.PHONY : navigator.i

# target to generate assembly for a file
navigator.s:
	$(MAKE) -f CMakeFiles/navigator.dir/build.make CMakeFiles/navigator.dir/navigator.s
.PHONY : navigator.s

# target to build an object file
obstacle_converter.o:
	$(MAKE) -f CMakeFiles/obstacle_converter.dir/build.make CMakeFiles/obstacle_converter.dir/obstacle_converter.o
.PHONY : obstacle_converter.o

# target to preprocess a source file
obstacle_converter.i:
	$(MAKE) -f CMakeFiles/obstacle_converter.dir/build.make CMakeFiles/obstacle_converter.dir/obstacle_converter.i
.PHONY : obstacle_converter.i

# target to generate assembly for a file
obstacle_converter.s:
	$(MAKE) -f CMakeFiles/obstacle_converter.dir/build.make CMakeFiles/obstacle_converter.dir/obstacle_converter.s
.PHONY : obstacle_converter.s

# target to build an object file
porttracker.o:
	$(MAKE) -f CMakeFiles/porttracker.dir/build.make CMakeFiles/porttracker.dir/porttracker.o
.PHONY : porttracker.o

# target to preprocess a source file
porttracker.i:
	$(MAKE) -f CMakeFiles/porttracker.dir/build.make CMakeFiles/porttracker.dir/porttracker.i
.PHONY : porttracker.i

# target to generate assembly for a file
porttracker.s:
	$(MAKE) -f CMakeFiles/porttracker.dir/build.make CMakeFiles/porttracker.dir/porttracker.s
.PHONY : porttracker.s

# target to build an object file
remotecontrol.o:
	$(MAKE) -f CMakeFiles/remotecontrol.dir/build.make CMakeFiles/remotecontrol.dir/remotecontrol.o
.PHONY : remotecontrol.o

# target to preprocess a source file
remotecontrol.i:
	$(MAKE) -f CMakeFiles/remotecontrol.dir/build.make CMakeFiles/remotecontrol.dir/remotecontrol.i
.PHONY : remotecontrol.i

# target to generate assembly for a file
remotecontrol.s:
	$(MAKE) -f CMakeFiles/remotecontrol.dir/build.make CMakeFiles/remotecontrol.dir/remotecontrol.s
.PHONY : remotecontrol.s

# target to build an object file
rootsolver_test.o:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/rootsolver_test.o
.PHONY : rootsolver_test.o

# target to preprocess a source file
rootsolver_test.i:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/rootsolver_test.i
.PHONY : rootsolver_test.i

# target to generate assembly for a file
rootsolver_test.s:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/rootsolver_test.s
.PHONY : rootsolver_test.s

# target to build an object file
ruddermain.o:
	$(MAKE) -f CMakeFiles/ruddermain.dir/build.make CMakeFiles/ruddermain.dir/ruddermain.o
.PHONY : ruddermain.o

# target to preprocess a source file
ruddermain.i:
	$(MAKE) -f CMakeFiles/ruddermain.dir/build.make CMakeFiles/ruddermain.dir/ruddermain.i
.PHONY : ruddermain.i

# target to generate assembly for a file
ruddermain.s:
	$(MAKE) -f CMakeFiles/ruddermain.dir/build.make CMakeFiles/ruddermain.dir/ruddermain.s
.PHONY : ruddermain.s

# target to build an object file
sailmain.o:
	$(MAKE) -f CMakeFiles/sailmain.dir/build.make CMakeFiles/sailmain.dir/sailmain.o
.PHONY : sailmain.o

# target to preprocess a source file
sailmain.i:
	$(MAKE) -f CMakeFiles/sailmain.dir/build.make CMakeFiles/sailmain.dir/sailmain.i
.PHONY : sailmain.i

# target to generate assembly for a file
sailmain.s:
	$(MAKE) -f CMakeFiles/sailmain.dir/build.make CMakeFiles/sailmain.dir/sailmain.s
.PHONY : sailmain.s

# target to build an object file
sailmain_keepalive.o:
	$(MAKE) -f CMakeFiles/sailmain_keepalive.dir/build.make CMakeFiles/sailmain_keepalive.dir/sailmain_keepalive.o
.PHONY : sailmain_keepalive.o

# target to preprocess a source file
sailmain_keepalive.i:
	$(MAKE) -f CMakeFiles/sailmain_keepalive.dir/build.make CMakeFiles/sailmain_keepalive.dir/sailmain_keepalive.i
.PHONY : sailmain_keepalive.i

# target to generate assembly for a file
sailmain_keepalive.s:
	$(MAKE) -f CMakeFiles/sailmain_keepalive.dir/build.make CMakeFiles/sailmain_keepalive.dir/sailmain_keepalive.s
.PHONY : sailmain_keepalive.s

# target to build an object file
sailor_main_iter_fn.o:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/sailor_main_iter_fn.o
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_main_iter_fn.o
.PHONY : sailor_main_iter_fn.o

# target to preprocess a source file
sailor_main_iter_fn.i:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/sailor_main_iter_fn.i
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_main_iter_fn.i
.PHONY : sailor_main_iter_fn.i

# target to generate assembly for a file
sailor_main_iter_fn.s:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/sailor_main_iter_fn.s
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_main_iter_fn.s
.PHONY : sailor_main_iter_fn.s

# target to build an object file
sailor_rudder_iter_fn.o:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/sailor_rudder_iter_fn.o
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_rudder_iter_fn.o
.PHONY : sailor_rudder_iter_fn.o

# target to preprocess a source file
sailor_rudder_iter_fn.i:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/sailor_rudder_iter_fn.i
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_rudder_iter_fn.i
.PHONY : sailor_rudder_iter_fn.i

# target to generate assembly for a file
sailor_rudder_iter_fn.s:
	$(MAKE) -f CMakeFiles/rootsolver_test.dir/build.make CMakeFiles/rootsolver_test.dir/sailor_rudder_iter_fn.s
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_rudder_iter_fn.s
.PHONY : sailor_rudder_iter_fn.s

# target to build an object file
sailor_statemachine.o:
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_statemachine.o
.PHONY : sailor_statemachine.o

# target to preprocess a source file
sailor_statemachine.i:
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_statemachine.i
.PHONY : sailor_statemachine.i

# target to generate assembly for a file
sailor_statemachine.s:
	$(MAKE) -f CMakeFiles/sailor_statemachine.dir/build.make CMakeFiles/sailor_statemachine.dir/sailor_statemachine.s
.PHONY : sailor_statemachine.s

# target to build an object file
sailor_transitions.o:
	$(MAKE) -f CMakeFiles/sailor_transitions.dir/build.make CMakeFiles/sailor_transitions.dir/sailor_transitions.o
.PHONY : sailor_transitions.o

# target to preprocess a source file
sailor_transitions.i:
	$(MAKE) -f CMakeFiles/sailor_transitions.dir/build.make CMakeFiles/sailor_transitions.dir/sailor_transitions.i
.PHONY : sailor_transitions.i

# target to generate assembly for a file
sailor_transitions.s:
	$(MAKE) -f CMakeFiles/sailor_transitions.dir/build.make CMakeFiles/sailor_transitions.dir/sailor_transitions.s
.PHONY : sailor_transitions.s

# target to build an object file
simulator.o:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/simulator.o
.PHONY : simulator.o

# target to preprocess a source file
simulator.i:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/simulator.i
.PHONY : simulator.i

# target to generate assembly for a file
simulator.s:
	$(MAKE) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/simulator.s
.PHONY : simulator.s

# target to build an object file
skipper.o:
	$(MAKE) -f CMakeFiles/skipper.dir/build.make CMakeFiles/skipper.dir/skipper.o
.PHONY : skipper.o

# target to preprocess a source file
skipper.i:
	$(MAKE) -f CMakeFiles/skipper.dir/build.make CMakeFiles/skipper.dir/skipper.i
.PHONY : skipper.i

# target to generate assembly for a file
skipper.s:
	$(MAKE) -f CMakeFiles/skipper.dir/build.make CMakeFiles/skipper.dir/skipper.s
.PHONY : skipper.s

# target to build an object file
skipper2.o:
	$(MAKE) -f CMakeFiles/skipper2.dir/build.make CMakeFiles/skipper2.dir/skipper2.o
.PHONY : skipper2.o

# target to preprocess a source file
skipper2.i:
	$(MAKE) -f CMakeFiles/skipper2.dir/build.make CMakeFiles/skipper2.dir/skipper2.i
.PHONY : skipper2.i

# target to generate assembly for a file
skipper2.s:
	$(MAKE) -f CMakeFiles/skipper2.dir/build.make CMakeFiles/skipper2.dir/skipper2.s
.PHONY : skipper2.s

# target to build an object file
system-state.o:
	$(MAKE) -f CMakeFiles/system-state.dir/build.make CMakeFiles/system-state.dir/system-state.o
.PHONY : system-state.o

# target to preprocess a source file
system-state.i:
	$(MAKE) -f CMakeFiles/system-state.dir/build.make CMakeFiles/system-state.dir/system-state.i
.PHONY : system-state.i

# target to generate assembly for a file
system-state.s:
	$(MAKE) -f CMakeFiles/system-state.dir/build.make CMakeFiles/system-state.dir/system-state.s
.PHONY : system-state.s

# target to build an object file
testaufruf.o:
	$(MAKE) -f CMakeFiles/testaufruf.dir/build.make CMakeFiles/testaufruf.dir/testaufruf.o
.PHONY : testaufruf.o

# target to preprocess a source file
testaufruf.i:
	$(MAKE) -f CMakeFiles/testaufruf.dir/build.make CMakeFiles/testaufruf.dir/testaufruf.i
.PHONY : testaufruf.i

# target to generate assembly for a file
testaufruf.s:
	$(MAKE) -f CMakeFiles/testaufruf.dir/build.make CMakeFiles/testaufruf.dir/testaufruf.s
.PHONY : testaufruf.s

# target to build an object file
windcleaner.o:
	$(MAKE) -f CMakeFiles/windcleaner.dir/build.make CMakeFiles/windcleaner.dir/windcleaner.o
.PHONY : windcleaner.o

# target to preprocess a source file
windcleaner.i:
	$(MAKE) -f CMakeFiles/windcleaner.dir/build.make CMakeFiles/windcleaner.dir/windcleaner.i
.PHONY : windcleaner.i

# target to generate assembly for a file
windcleaner.s:
	$(MAKE) -f CMakeFiles/windcleaner.dir/build.make CMakeFiles/windcleaner.dir/windcleaner.s
.PHONY : windcleaner.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... aisEval"
	@echo "... destination_converter"
	@echo "... dtom"
	@echo "... edit_cache"
	@echo "... eposdebug"
	@echo "... flag-checker"
	@echo "... global_skipper"
	@echo "... gps"
	@echo "... imucleaner"
	@echo "... mtod"
	@echo "... navigator"
	@echo "... obstacle_converter"
	@echo "... porttracker"
	@echo "... rebuild_cache"
	@echo "... remotecontrol"
	@echo "... rootsolver_test"
	@echo "... ruddermain"
	@echo "... sailmain"
	@echo "... sailmain_keepalive"
	@echo "... sailor_statemachine"
	@echo "... sailor_transitions"
	@echo "... simulator"
	@echo "... skipper"
	@echo "... skipper2"
	@echo "... system-state"
	@echo "... testaufruf"
	@echo "... windcleaner"
	@echo "... RudderMotor.o"
	@echo "... RudderMotor.i"
	@echo "... RudderMotor.s"
	@echo "... SailMotor.o"
	@echo "... SailMotor.i"
	@echo "... SailMotor.s"
	@echo "... Ship.o"
	@echo "... Ship.i"
	@echo "... Ship.s"
	@echo "... aisEval.o"
	@echo "... aisEval.i"
	@echo "... aisEval.s"
	@echo "... destination_converter.o"
	@echo "... destination_converter.i"
	@echo "... destination_converter.s"
	@echo "... dtom.o"
	@echo "... dtom.i"
	@echo "... dtom.s"
	@echo "... eposdebug.o"
	@echo "... eposdebug.i"
	@echo "... eposdebug.s"
	@echo "... flag-checker.o"
	@echo "... flag-checker.i"
	@echo "... flag-checker.s"
	@echo "... global_skipper.o"
	@echo "... global_skipper.i"
	@echo "... global_skipper.s"
	@echo "... gps.o"
	@echo "... gps.i"
	@echo "... gps.s"
	@echo "... imucleaner.o"
	@echo "... imucleaner.i"
	@echo "... imucleaner.s"
	@echo "... mtod.o"
	@echo "... mtod.i"
	@echo "... mtod.s"
	@echo "... navigator.o"
	@echo "... navigator.i"
	@echo "... navigator.s"
	@echo "... obstacle_converter.o"
	@echo "... obstacle_converter.i"
	@echo "... obstacle_converter.s"
	@echo "... porttracker.o"
	@echo "... porttracker.i"
	@echo "... porttracker.s"
	@echo "... remotecontrol.o"
	@echo "... remotecontrol.i"
	@echo "... remotecontrol.s"
	@echo "... rootsolver_test.o"
	@echo "... rootsolver_test.i"
	@echo "... rootsolver_test.s"
	@echo "... ruddermain.o"
	@echo "... ruddermain.i"
	@echo "... ruddermain.s"
	@echo "... sailmain.o"
	@echo "... sailmain.i"
	@echo "... sailmain.s"
	@echo "... sailmain_keepalive.o"
	@echo "... sailmain_keepalive.i"
	@echo "... sailmain_keepalive.s"
	@echo "... sailor_main_iter_fn.o"
	@echo "... sailor_main_iter_fn.i"
	@echo "... sailor_main_iter_fn.s"
	@echo "... sailor_rudder_iter_fn.o"
	@echo "... sailor_rudder_iter_fn.i"
	@echo "... sailor_rudder_iter_fn.s"
	@echo "... sailor_statemachine.o"
	@echo "... sailor_statemachine.i"
	@echo "... sailor_statemachine.s"
	@echo "... sailor_transitions.o"
	@echo "... sailor_transitions.i"
	@echo "... sailor_transitions.s"
	@echo "... simulator.o"
	@echo "... simulator.i"
	@echo "... simulator.s"
	@echo "... skipper.o"
	@echo "... skipper.i"
	@echo "... skipper.s"
	@echo "... skipper2.o"
	@echo "... skipper2.i"
	@echo "... skipper2.s"
	@echo "... system-state.o"
	@echo "... system-state.i"
	@echo "... system-state.s"
	@echo "... testaufruf.o"
	@echo "... testaufruf.i"
	@echo "... testaufruf.s"
	@echo "... windcleaner.o"
	@echo "... windcleaner.i"
	@echo "... windcleaner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

