#! /bin/sh


case "$1" in
  start)
    slattach -p slip -s 115200 -L /dev/ttyUSB0 &
    sleep 1
    ifconfig sl0 192.168.33.3 pointopoint 192.168.33.2
    ;;
  stop)
    ifconfig sl0 down
    killall slattach
    ;;
  *)
    echo "Usage: /etc/init.d/serial {start|stop}"
    exit 1
esac

exit 0
